apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: adityavatsa08/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**.ts"
                    dest: .

        - image: adityavatsa08/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.js"
                    dest: .

        - image: adityavatsa08/tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.ts"
                    dest: .
